services:
  # Slack Bot Service
  slack-bot:
    build: .
    environment:
      - SERVICE_NAME=slack_bot
      - SLACK_BOT_PORT=8000
      - EXPERT_API_URL=http://expert-api:8000
      # Pass from host environment
      - DEBUG
      - LOG_LEVEL
      - SLACK_BOT_AUTH_TOKEN
      - SLACK_BOT_HOST
      - SLACK_BOT_SENTRY_DSN
    ports:
      - "3001:8000"
    depends_on:
      - expert-api
    restart: unless-stopped

  # Ingestor Service
  ingestor:
    build: .
    environment:
      - SERVICE_NAME=ingestor
      - INGESTOR_PORT=8000
      - TRUFFLE_DB_URL=postgresql://truffle:truffle@postgres:5432/truffle
      # Pass from host environment
      - DEBUG
      - INGESTOR_HOST
      - INGESTOR_SENTRY_DSN
      - LOG_LEVEL
      - OPENAI_API_KEY
      - SLACK_BOT_AUTH_TOKEN
    ports:
      - "3002:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Expert API Service
  expert-api:
    build: .
    environment:
      - SERVICE_NAME=expert_api
      - EXPERT_API_PORT=8000
      - TRUFFLE_DB_URL=postgresql://truffle:truffle@postgres:5432/truffle
      # Pass from host environment
      - DEBUG
      - EXPERT_API_HOST
      - EXPERT_API_SENTRY_DSN
      - LOG_LEVEL
    ports:
      - "3003:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=truffle
      - POSTGRES_USER=truffle
      - POSTGRES_PASSWORD=truffle
      # Configure authentication method for network connections
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount initialization script
      - ./docker/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5439:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U truffle -d truffle"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_data:
