services:
  # Slack Bot Service
  slack-bot:
    build: .
    environment:
      - SERVICE_NAME=slack_bot
      - SLACK_BOT_PORT=8000
      - EXPERT_API_URL=http://expert-api:8000
      # Pass from host environment
      - DEBUG
      - LOG_LEVEL
      - SLACK_BOT_AUTH_TOKEN
      - SLACK_BOT_HOST
      - SLACK_BOT_SENTRY_DSN
    ports:
      - "3001:8000"
    depends_on:
      - expert-api
    restart: unless-stopped

  # Ingestor Service
  ingestor:
    build: .
    environment:
      - SERVICE_NAME=ingestor
      - INGESTOR_PORT=8000
      # Pass from host environment
      - DEBUG
      - INGESTOR_HOST
      - INGESTOR_SENTRY_DSN
      - LOG_LEVEL
      - OPENAI_API_KEY
      - SLACK_BOT_AUTH_TOKEN
      - TRUFFLE_DB_URL
    ports:
      - "3002:8000"
    depends_on:
      - postgres
    restart: unless-stopped

  # Expert API Service
  expert-api:
    build: .
    environment:
      - SERVICE_NAME=expert_api
      - EXPERT_API_PORT=8000
      # Pass from host environment
      - DEBUG
      - EXPERT_API_HOST
      - EXPERT_API_SENTRY_DSN
      - LOG_LEVEL
      - TRUFFLE_DB_URL
    ports:
      - "3003:8000"
    depends_on:
      - postgres
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: truffle
      POSTGRES_USER: truffle_user
      POSTGRES_PASSWORD: truffle_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./doc/setup-db.sql:/docker-entrypoint-initdb.d/setup-db.sql
    ports:
      - "5434:5432"
    restart: unless-stopped

volumes:
  postgres_data:
